Fix eslint with update to globals dev dependency
Fixes this error when running eslint in vscode:
Error: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.